# Generated by Django 2.2.4 on 2020-05-30 18:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroudImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='background_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('brand_img', models.ImageField(upload_to='brand_img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.PositiveIntegerField(blank=True)),
                ('is_send_to_my_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('in_stock', models.BooleanField(default=True)),
                ('details', models.TextField(max_length=500)),
                ('video_details', models.URLField(help_text='provide a youtube link', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='all.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_detail', models.TextField()),
                ('rating_star', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='all.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_name', models.CharField(max_length=50)),
                ('trend_img', models.ImageField(upload_to='trend_img')),
                ('trend_outfit_name', models.CharField(max_length=50)),
                ('trend_outfit_img', models.ImageField(upload_to='trend_outfit_img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=50)),
                ('rating_star', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_review', to='all.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoReviewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.PositiveIntegerField(default=0)),
                ('disagreed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_review_count', to='all.VideoReview')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('division', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chottogram', 'Chottogram'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet')], max_length=100, null=True)),
                ('city', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chottogram', 'Chottogram'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet')], max_length=100, null=True)),
                ('area', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chottogram', 'Chottogram'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('mamaaaa', 'mamaaaa')], max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=50)),
                ('sub_category_img', models.ImageField(upload_to='sub_category_img')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='all.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.PositiveIntegerField(default=0)),
                ('disagreed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_count', to='all.Review')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWithQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost', models.PositiveIntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_with_quantity', to='all.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='all.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='all.SubCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='all.Trending'),
        ),
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sub_total', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=30)),
                ('receiver_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('receiver_other_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('receiver_division', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chottogram', 'Chottogram'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet')], max_length=100)),
                ('receiver_city', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chottogram', 'Chottogram'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet')], max_length=100)),
                ('receiver_area', models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chottogram', 'Chottogram'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('mamaaaa', 'mamaaaa')], max_length=100)),
                ('receiver_address', models.TextField(blank=True, max_length=200)),
                ('is_confirm', models.BooleanField(default=False)),
                ('is_payment_confirm', models.BooleanField(default=False)),
                ('payment', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processing', models.BooleanField(default=False)),
                ('is_placed', models.BooleanField(default=False)),
                ('is_on_road', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('my_bag', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_order', to='all.MyBag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mybag',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='my_bag', to='all.ProductWithQuantity'),
        ),
        migrations.AddField(
            model_name='mybag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
