# Generated by Django 3.1.2 on 2021-01-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
