# Generated by Django 2.2.4 on 2020-06-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcount',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all.Review'),
        ),
    ]
