# Generated by Django 3.1.2 on 2020-11-18 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcount',
            name='agreed',
        ),
        migrations.RemoveField(
            model_name='reviewcount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviewcount',
            name='disagreed',
        ),
        migrations.RemoveField(
            model_name='reviewcount',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewcount',
            name='user',
        ),
        migrations.CreateModel(
            name='ReviewCountForDisagree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disagreed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all.review')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCountForAgree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all.review')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
