# Generated by Django 2.2.4 on 2020-06-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_auto_20200602_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreviewcount',
            name='video_review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all.VideoReview'),
        ),
    ]
