# Generated by Django 3.1.5 on 2021-06-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_remove_category_category_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcount',
            name='agreed',
        ),
        migrations.RemoveField(
            model_name='reviewcount',
            name='disagreed',
        ),
        migrations.RemoveField(
            model_name='videoreviewcount',
            name='agreed',
        ),
        migrations.RemoveField(
            model_name='videoreviewcount',
            name='disagreed',
        ),
        migrations.AddField(
            model_name='reviewcount',
            name='vote',
            field=models.CharField(choices=[('agreed', 'agreed'), ('disagreed', 'disagreed')], default='agreed', max_length=10),
        ),
        migrations.AddField(
            model_name='videoreviewcount',
            name='vote',
            field=models.CharField(choices=[('agreed', 'agreed'), ('disagreed', 'disagreed')], default='agreed', max_length=10),
        ),
    ]
