# Generated by Django 3.1.2 on 2020-12-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_productinfo_youwillget'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productwithquantity',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10),
        ),
    ]
