# Generated by Django 2.2.4 on 2020-06-02 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all', '0003_auto_20200602_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcount',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
