# Generated by Django 3.1.5 on 2021-06-24 13:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_auto_20210624_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='payment',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery')], max_length=100),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='receiver_address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='receiver_area',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='receiver_city',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='receiver_division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Sylhet', 'Sylhet'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='receiver_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='receiver_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
