# Generated by Django 3.1.5 on 2021-06-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_auto_20210616_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myorder',
            old_name='is_confirm',
            new_name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='is_payment_confirm',
        ),
        migrations.AddField(
            model_name='myorder',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='After user confirm by call then it will checked!'),
        ),
    ]
