# Generated by Django 3.1.5 on 2021-06-15 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0004_auto_20210616_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybag',
            name='product_with_quantity',
        ),
        migrations.AddField(
            model_name='myorder',
            name='is_completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productwithquantity',
            name='my_bag',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='product_with_quantity', to='all.mybag'),
        ),
    ]
