# Generated by Django 3.1.2 on 2020-12-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0004_auto_20201226_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.CreateModel(
            name='ProductAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField(default=5)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all.product')),
            ],
        ),
    ]
