# Generated by Django 3.1.2 on 2021-01-05 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all', '0005_auto_20201226_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoreviewcount',
            name='agreed',
        ),
        migrations.RemoveField(
            model_name='videoreviewcount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videoreviewcount',
            name='disagreed',
        ),
        migrations.RemoveField(
            model_name='videoreviewcount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videoreviewcount',
            name='video_review',
        ),
        migrations.CreateModel(
            name='VideoReviewCountForDisagree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disagreed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('video_review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all.videoreview')),
            ],
        ),
        migrations.CreateModel(
            name='VideoReviewCountForAgree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('video_review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='all.videoreview')),
            ],
        ),
    ]
