# Generated by Django 3.1.2 on 2021-01-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0006_auto_20210105_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_trail',
            field=models.BooleanField(default=False),
        ),
    ]
