# Generated by Django 3.1.2 on 2021-01-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0007_product_has_trail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_trail',
            new_name='has_trial',
        ),
    ]
