# Generated by Django 3.1.2 on 2021-01-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0008_auto_20210106_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwithquantity',
            name='add_as_trial',
            field=models.BooleanField(default=False),
        ),
    ]
